# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Converor(object):
    def setupUi(self, Converor):
        Converor.setObjectName("Converor")
        Converor.resize(182, 231)
        self.centralwidget = QtWidgets.QWidget(Converor)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 161, 181))
        self.groupBox.setObjectName("groupBox")
        self.Run = QtWidgets.QPushButton(self.groupBox)
        self.Run.setGeometry(QtCore.QRect(10, 150, 141, 23))
        self.Run.setObjectName("Run")
        self.incoming_file = QtWidgets.QLabel(self.groupBox)
        self.incoming_file.setGeometry(QtCore.QRect(10, 60, 141, 20))
        self.incoming_file.setText("")
        self.incoming_file.setObjectName("incoming_file")
        self.end_at = QtWidgets.QLabel(self.groupBox)
        self.end_at.setGeometry(QtCore.QRect(10, 110, 141, 20))
        self.end_at.setText("")
        self.end_at.setObjectName("end_at")
        self.Open_file = QtWidgets.QPushButton(self.groupBox)
        self.Open_file.setGeometry(QtCore.QRect(10, 20, 141, 23))
        self.Open_file.setObjectName("Open_file")
        self.start_at = QtWidgets.QLabel(self.groupBox)
        self.start_at.setGeometry(QtCore.QRect(10, 80, 141, 20))
        self.start_at.setText("")
        self.start_at.setObjectName("start_at")
        Converor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Converor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 182, 20))
        self.menubar.setObjectName("menubar")
        Converor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Converor)
        self.statusbar.setObjectName("statusbar")
        Converor.setStatusBar(self.statusbar)

        self.retranslateUi(Converor)
        QtCore.QMetaObject.connectSlotsByName(Converor)

    def retranslateUi(self, Converor):
        _translate = QtCore.QCoreApplication.translate
        Converor.setWindowTitle(_translate("Converor", "MainWindow"))
        self.groupBox.setTitle(_translate("Converor", "Конвертор прайсу"))
        self.Run.setText(_translate("Converor", "Виконати"))
        self.Open_file.setText(_translate("Converor", "Оберіть файл"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Converor = QtWidgets.QMainWindow()
    ui = Ui_Converor()
    ui.setupUi(Converor)
    Converor.show()
    sys.exit(app.exec_())
